### ISSUE TITLE
Monitoring stack should be added by default

### ISSUE THREAD

**Issue by hev** [aerospike/aerolab#100]
This seems potentially more problematic than #99 but I still the trade-offs would be worthwhile. Again, user could opt out but the default should be that when create a cluster, a client is also created called amc (if one doesn't already exist). Again, this will impact scripts created out there and will slow down the standard cluster create but encourages adoption of AMC.

**Comment by robertglonek** [comment]
I'll have to reject this one. Problems:

1. I really cannot programmatically know what the user wants. For example a user could be creating 4 clusters in active xdr setup and adding them all to a single AMS, or the user could be creating just one cluster for AMS. If AMS already exists, and a user creates a new cluster, do they want it connected to this AMS or are they wanting to create a new AMS for this one? Does the user want AMS or are they testing the behaviour of an asadm command and then killing the cluster? There is simply too many unknowns to force such a creation.

2. Also, possibly more importantly, on GCP and AWS platforms extra information is required to create an AMS client - such as instance type and root device size among other options. On docker, one might want to expose an AMS port by mapping it to another port, for example. There are shared switches used for both AMS and Cluster creation and trying to allow adding AMS creating to cluster create would require an unreasonable number of duplicated switches with possibly --ams- prefix at the very least.

**Comment by hev** [comment]
Fair enough, I thought this was likely somewhat problematic. I mostly think exporter should be on by default (#99) - I can close this one for you.
