### ISSUE TITLE
Cluster and Client list are very wide

### ISSUE THREAD

**Issue by robertglonek** [aerospike/aerolab#177]
Proposal to provide an option to by default shorten the `cluster list` and `client list` outputs, with an option of `--full` for full view. Full view would still have the `--no-pager` to disable pager and by default would provide a pager. The Shortened list would not use a pager. Proposal: order items in importance and work out what we can display based on screen width. Inventory listing should always show everything.

What is important to users in terms of data they want/need to see?

**Comment by hev** [comment]
Name/Node ID 
State
Public IP
Private IP
Exposed Ports
Firewalls

**Comment by robertglonek** [comment]
@hev Do we need the private AND public IP in this listing? You can get a nicely parseable and greppable output with internal and external IP by running `aerolab cluster list --ip` already. We could potentially skip those from this output.

For the list itself, we were thinking (docker):
* ClusterName, NodeNo, Private IP, State, Aerospike Version, Firewalls, Owner, Exposed Port
And AWS/GCP:
* ClusterName, NodeNo, Public IP, State, Aerospike Version, Firewalls, Owner, Expires In, Instance Running Cost

For clients we would need to fit as well, at bare minimum: Access URL, Access Port, Client Type (all 3 for all backends). Access Port == Exposed Port for docker.

For multi-tenancy, owner is fairly important, Aerospike Version for multi-cluster listings too, and the 2 extra fields for AWS/GCP are also important. We should be able to get it nice and short though if we also only provide 1 IP in the listing.

We would in this case already be removing, from cluster/client list (but keeping in inventory list command) the following:
* instance ID, image ID, Arch, One IP listing, Distribution, OS Version

Thoughts?

----

On a separate note, I am torn between what we do with the pager. For `inventory list` pager is important, and `--no-pager` fits the systemctl/journalctl designs as well. I can make the last output not disappear when you exit the pager as well, if you think that's useful.

For the smaller size cluster/client list, I would suggest:
* default: small list, no pager
* add option --pager if someone wants a pager for the small listing
* add option --full which will display full output
* then the question is what do we do about the pager for full, how to enable/disable; inconsistency

Another solution is to keep pager always enabled and provide the user with a doc explaining how to default to no-pager (since it's a simple `aerolab config defaults -k '*.NoPager' -v true` - and that turns off pager by default).

Thoughts on that?

**Comment by robertglonek** [comment]
@hev @dotyjim-work 

Ok, I think I figured it out. It's going to be different than what we discussed, I think for the better. Dev build is on the way, please test and give feedback.

The features are as follows (discussed this a while back with Jim :))
1. Default: no pager
2. To enable pager, run `--pager`
3. All systems shows the same columns (same cluster list columns as the listing of cluster in inventory list)
4. Without pager, the columns do get truncated, so instead of getting wrapped, if the terminal size is too small, they will truncate to terminal size. This way we see as much as possible each time, no matter the screen size
5. I tried to order the columns in most-important to least-important so that more important columns have higher chance of displaying
6. When piping via grep (or other tool), the output looks almost the same as without piping, just black-and-white. This makes grepping easier. The output also NEVER gets truncated if piping via grep (or other tool)
7. Added --sort-by option
8. The comments under the tables (starting with *) are sent to stderr, while the tables get sent to stdout. This makes grepping easier.

**Comment by robertglonek** [comment]
Discussed off-thread. Implemented in 7.2.0. Closing.
