### ISSUE TITLE
WebUI - HA for ssh keys

### ISSUE THREAD

**Issue by robertglonek** [aerospike/aerolab#258]
Allow the option of storing SSH keys for AWS/GCP backends in a central or distributed way to allow for aerolab webui to function in HA mode. Consider inventory API output sharing in the same fashion(?) so only one machine pulls inventory at a time. Closely think this through together with "multi-region for aws" ticket.

**Comment by dotyjim-work** [comment]
I think we discussed that we can provide a file with user keys for now.

**Comment by robertglonek** [comment]
Closing as won't do, we will just deploy aerolab webui on 2 regions separately.
