### ISSUE TITLE
Trim empty space in path string

### ISSUE THREAD

**Issue by volmarl** [aerospike/aerolab#384]
Minor issue, but a trailing space accidentally left in the path string will cause the get logs command to fail without explanation.

`$ aerolab logs get --name 'testcluster' --path '/tmp/collect_info_20240802_194533.tgz ' --destination '-'

2024/08/02 19:49:23 +0000 Running logs.get
2024/08/02 19:49:27 +0000 log cat error: Process exited with status 1

-=-=-=-=- [ExitCode] 1 -=-=-=-=-
exit status 1
-=-=-=-=- [END] -=-=-=-=-`

**Comment by robertglonek** [comment]
Fixed
