### ISSUE TITLE
error when attempting to run-ingest on original path

### ISSUE THREAD

**Issue by volmarl** [aerospike/aerolab#387]
`$ aerolab agi run-ingest --name 'repro-lucien'

2024/08/05 16:07:46 +0000 could not get current config: error running `cat /opt/agi/ingest.yaml`: dial tcp 18.237.217.163:22: connect: connection refused: 

-=-=-=-=- [ExitCode] 1 -=-=-=-=-
exit status 1
-=-=-=-=- [END] -=-=-=-=-`

**Comment by robertglonek** [comment]
Fixed, deploying. was caused by ubuntu-s unattended upgrades
