### ISSUE TITLE
Improve interface for time ranges

### ISSUE THREAD

**Issue by tplacker-aerospike** [aerospike/aerolab#410]
Manually typing in a time range and trying to get the right format is a pain, and the error messages a) don't show up until you hit run and b) aren't very helpful. Calendar picker, time zone pulldown, and autocompleting time-of-day would make things a lot nicer and hopefully not be too much work.

**Comment by robertglonek** [comment]
For now, resolved by adding date/time mask (helper to type in dates and times). https://github.com/aerospike/aerolab/commit/c453d521bd19218791f867907daa07dd2c4474d8
