### ISSUE TITLE
Download logs in parallel

### ISSUE THREAD

**Issue by kportertx** [aerospike/aerolab#91]

**Comment by robertglonek** [comment]
Will add this feature and a switch to enable/disable that in next release. I think I’ll essentially add —parallel=int where int is the count of machines to do in parallel at once, defaulting to 1. This will allow to do eg —parallel=10 on clusters of 100+ nodes not to overload the local system when downloading.

**Comment by robertglonek** [comment]
Fixed in commit https://github.com/aerospike/aerolab/commit/a14576963414fed2a8a164d3d32b7702bca2e194

Will release in 6.1.0
