### ISSUE TITLE
Make Aerospike Prometheus the default

### ISSUE THREAD

**Issue by hev** [aerospike/aerolab#96]
The latest monitoring stack release eliminates some instance of hardcoding related to the data source. This appears to break dashboard functionality in the UI in some places. This can be fixed by the user by setting Aerospike Prometheus as the default data source. Ideally this can be configured that way when Aerolab configures AMS. 

<img width="1484" alt="Data_sources_-_Connections_-_Grafana" src="https://github.com/aerospike/aerolab/assets/20188639/5189390e-c241-46e9-a343-00ea02b93e35">

**Comment by robertglonek** [comment]
Actually I get the datasources yaml file from [AMS stack](https://raw.githubusercontent.com/aerospike/aerospike-monitoring/master/config/grafana/provisioning/datasources/all.yaml). Should we change the isDefault there?
