### ISSUE TITLE
Exporter should be added by default

### ISSUE THREAD

**Issue by hev** [aerospike/aerolab#99]
Adding monitoring should not require extra steps, and instead be the default cause for `aerolab cluster create`. Users could opt out of it, with a flag like '--no-exporter` but the default should be to add it.

Downside, this slows down standard cluster creation and may cause some scripts to throw warnings but seems worth the trade off IMO.

**Comment by robertglonek** [comment]
Don't be implementing due to version compatibility issues and configuration difficulty with custom ape.toml when security/tls is enabled. We will have an alternative option in 7.2 with aerolab-generated getting-started scripts.
